{{- if .Values.mcpServers.gmail.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mcpServers.gmail.name }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "stockripperv2.labels" . | nindent 4 }}
    app.kubernetes.io/component: mcp-server
    app.kubernetes.io/name: gmail-mcp
spec:
  type: {{ .Values.mcpServers.gmail.service.type }}
  ports:
    - port: {{ .Values.mcpServers.gmail.service.port }}
      targetPort: {{ .Values.mcpServers.gmail.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: gmail-mcp
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

# Contains AI-generated edits.
