{{- if .Values.mailer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mailer.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.mailer.name }}
    component: agent
    chart: {{ include "stockripperv2.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.mailer.service.type }}
  ports:
    - port: {{ .Values.mailer.service.port }}
      targetPort: {{ .Values.mailer.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.mailer.name }}
    release: {{ .Release.Name }}
{{- end }}
