{{- if .Values.marketAnalyst.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.marketAnalyst.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.marketAnalyst.name }}
    component: agent
    chart: {{ include "stockripperv2.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.marketAnalyst.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.marketAnalyst.name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.marketAnalyst.name }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Values.marketAnalyst.name }}
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.marketAnalyst.image.repository }}:{{ .Values.marketAnalyst.image.tag }}"
          imagePullPolicy: {{ .Values.marketAnalyst.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.marketAnalyst.service.targetPort }}
              protocol: TCP
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secret
                  key: api-key
            - name: OPENAI_MODEL
              value: {{ .Values.env.openai.model | quote }}
            - name: ALPACA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: alpaca-secret
                  key: api-key
            - name: ALPACA_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: alpaca-secret
                  key: secret-key
            - name: ALPACA_BASE_URL
              value: {{ .Values.marketAnalyst.env.ALPACA_BASE_URL | quote }}
            - name: ALPACA_MCP_URL
              value: {{ .Values.marketAnalyst.env.ALPACA_MCP_URL | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.env.logging.level | quote }}
            - name: LOG_FORMAT
              value: {{ .Values.env.logging.format | quote }}
            - name: A2A_TIMEOUT
              value: {{ .Values.env.a2a.timeout | quote }}
            - name: A2A_RETRY_ATTEMPTS
              value: {{ .Values.env.a2a.retryAttempts | quote }}
            - name: A2A_DISCOVERY_ENABLED
              value: {{ .Values.env.a2a.discoveryEnabled | quote }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /.well-known/agent.json
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.marketAnalyst.resources | nindent 12 }}
      restartPolicy: Always
{{- end }}
