apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "stockripperv2.labels" . | nindent 4 }}
    app.kubernetes.io/component: namespace

# Contains AI-generated edits.
