{{- if .Values.secrets.openai.create }}
apiVersion: v1
kind: Secret
metadata:
  name: openai-secret
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "stockripperv2.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.secrets.openai.data.api-key | b64enc | quote }}
---
{{- end }}

{{- if .Values.secrets.alpaca.create }}
apiVersion: v1
kind: Secret
metadata:
  name: alpaca-secret
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "stockripperv2.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.secrets.alpaca.data.api-key | b64enc | quote }}
  secret-key: {{ .Values.secrets.alpaca.data.secret-key | b64enc | quote }}
---
{{- end }}

{{- if .Values.secrets.gmail.create }}
apiVersion: v1
kind: Secret
metadata:
  name: gmail-credentials
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "stockripperv2.labels" . | nindent 4 }}
type: Opaque
data:
  credentials.json: {{ .Values.secrets.gmail.data.credentials.json | quote }}
  token.json: {{ .Values.secrets.gmail.data.token.json | quote }}
{{- end }}

# Contains AI-generated edits.
