{{- if .Values.secrets.openai.create }}
apiVersion: v1
kind: Secret
metadata:
  name: openai-secret
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "stockripperv2.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.secrets.openai.data.apiKey | b64enc | quote }}
---
{{- end }}

{{- if .Values.secrets.alpaca.create }}
apiVersion: v1
kind: Secret
metadata:
  name: alpaca-secret
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "stockripperv2.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.secrets.alpaca.data.apiKey | b64enc | quote }}
  secret-key: {{ .Values.secrets.alpaca.data.secretKey | b64enc | quote }}
---
{{- end }}

{{- if .Values.secrets.gmail.create }}
apiVersion: v1
kind: Secret
metadata:
  name: gmail-credentials
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "stockripperv2.labels" . | nindent 4 }}
type: Opaque
data:
  credentials.json: {{ .Values.secrets.gmail.data.credentialsJson | quote }}
  token.json: {{ .Values.secrets.gmail.data.tokenJson | quote }}
{{- end }}

