# Global configuration
global:
  namespace: stockripper
  imageRegistry: ""
  imagePullPolicy: Never
  
# Common environment variables
env:
  openai:
    apiKey: ""  # Set via secret
    model: "gpt-4o-mini"
  logging:
    level: "INFO"
    format: "json"
  a2a:
    timeout: 30
    retryAttempts: 3
    discoveryEnabled: true

# Market Analyst Agent
marketAnalyst:
  enabled: true
  name: market-analyst
  replicaCount: 1
  image:
    repository: stockripper/market-analyst
    tag: "latest"
    pullPolicy: Never
  
  service:
    type: ClusterIP
    port: 8001
    targetPort: 8001
  
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: market-analyst.local
        paths:
          - path: /
            pathType: Prefix
  
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  
  env:
    ALPACA_API_KEY: ""  # Set via secret
    ALPACA_SECRET_KEY: ""  # Set via secret
    ALPACA_BASE_URL: "https://paper-api.alpaca.markets"
    ALPACA_MCP_URL: ""

# Planner Agent  
planner:
  enabled: true
  name: planner
  replicaCount: 1
  image:
    repository: stockripper/planner
    tag: "latest"
    pullPolicy: Never
  
  service:
    type: ClusterIP
    port: 8002
    targetPort: 8002
  
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: planner.local
        paths:
          - path: /
            pathType: Prefix
  
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  
  env:
    MARKET_ANALYST_URL: "http://market-analyst:8001"

# Mailer Agent
mailer:
  enabled: true
  name: mailer
  replicaCount: 1
  image:
    repository: stockripper/mailer
    tag: "latest"
    pullPolicy: Never
  
  service:
    type: ClusterIP
    port: 8003
    targetPort: 8003
  
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: mailer.local
        paths:
          - path: /
            pathType: Prefix
  
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 150m
      memory: 128Mi  
  env:
    DEFAULT_EMAIL_RECIPIENT: "admin@stockripper.com"

# Secrets configuration
secrets:
  openai:
    create: true
    data:
      apiKey: ""  # Base64 encoded
  
  alpaca:
    create: true
    data:
      apiKey: ""  # Base64 encoded
      secretKey: ""  # Base64 encoded
  
  gmail:
    create: true
    data:
      credentialsJson: ""  # Base64 encoded credentials file
      tokenJson: ""  # Base64 encoded token file

# ServiceMonitor for Prometheus (optional)
monitoring:
  enabled: false
  serviceMonitor:
    enabled: false
    namespace: monitoring
    labels: {}

# Contains AI-generated edits.
